web:
  build: .
  command: node index-db.js
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    MYSQL_DATABASE: docker-demo
    MYSQL_USER: docker-demo
    MYSQL_PASSWORD: docker-demo-secure-pass
    MYSQL_HOST: db
db:
  image: orchardup/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: docker-demo
    MYSQL_USER: docker-demo
    MYSQL_PASSWORD: docker-demo-secure-pass
